### ISSUE TITLE
Can I have this and another version of Python at the same time?

### ISSUE THREAD

**Issue by viveksh1** [microsoft/coding-pack-for-python#9]
If I have the Python Coding Pack for VS Code installed, and I want to install Python for Visual Studio (which includes Python 3.7.8) will both Python versions interfere with each other? What about the system path? Can they coexist peacefully?

**Comment by VladPutinEu** [comment]
@zooba Is this possible?

**Comment by viveksh1** [comment]
Closing, Visual Studio does not add Python 3.7.8 to PATH.
